site_name: GLMC-DISPATCHES
site_logo: img/dispatches_logo-darkbg.svg
nav:
  - Home: index.md
  - Team: team.md
  - Download: download.md
  - Media: media.md
docs_dir: src
site_dir: docs
theme:
  name: cerulean
  custom_dir: 'gmlc_theme/'
extra_css:
  - css/site.css
